language: ruby
cache: bundler
rvm: 2.1.1
install:
- bundle install
- nvm install 0.10.30
- npm install -g bower
- npm install -g grunt-cli
- npm install
- bower install
before_script:
- openssl aes-256-cbc -k $SECRET -in _deploy/deploy.key.enc -d -a -out ~/.ssh/deploy.key
- chmod 600 ~/.ssh/deploy.key
script:
- grunt ci --user=$USER
branches:
  only:
    - master
    - test
env:
  global:
  - secure: GAA53muGhqM+lBCS88NQW1j8OI42c7taDEdr0O4lmjNS6/nSrylJ311w6u3f6YjaMUagQpMrbg5+xY69dVzdpdXmbLPRCQ3yp3TTHZuV3Vjn6VxzoqZoL2xITyYpgHZJQQhyh20CIZv3ZcBElM2SDZ6iffyYVqXoHETgQrz17UI=
  - secure: Muiu9PiGIRtLBEm0r+Ujx6GkF3qAEC/zokLcic2E+gdFEvoTdj86dXC6PylnIb5nchIf8Ikn/89BLgpr7RaNPgQl1B79WH65FKP0wtroqxV5ZNeMn8C3O6hDnBx8qT3AvDi9OBZKfL/43fENrGrxZSUN44I0eU0WErRgIHmXoPk=
