language: ruby
rvm: 2.1.1
install: # override default "bundle install --deployment" and force install with PATH inclusion
- bundle install
- nvm install 0.10.29
- npm install -g bower
- npm install -g grunt-cli
- npm install
- cd site
- bower install
- cd ..
before_script:
- openssl aes-256-cbc -k $SECRET -in .deploy/deploy.key.enc -d -a -out ~/.ssh/deploy.key
- chmod 600 ~/.ssh/deploy.key
script:
- grunt ci --user=$USER
env:
  global:
  - secure: BE7CIal7UNLVBoyaL0fIvzHB9aROMBWzqTPW7OKXJr15Y4/x+MB4TqKJkDW5Ddq5kOE7kbtF3lftvo+5P5rwxvIdI64vPIuKXb0BUjvr7dS0B+UzYNBN6Y5/QHcsq9Aa366tG6vGi76iTVN1fWCnkBQ0Xq6jylTBcPq8FiD0okA=
  - secure: MpIDfNRJYn5bxuirGPqyIWipn0BJR5G/TL0tpEDpMolDljH91lf455me5dGM1j6VTic4wGb8LmAi/P+qvSKUzBMl/LQxBiQE47z620Sjvm9PjTarczzCZU+s82ZsVZQDoncB2q0VAFhLa0gJd9nk0FUZDEpt1E6YVRDjUPYBAWM=
