name: Coding Zeit
tagline: A developer blog on web technologies.
url: https://coding.maier.asia
author: Thilo Maier
twitter_username: mdotasia
description: Coding Zeit is a developer blog on web technologies.

encoding: utf-8
timezone: America/New_York
# permalink:
# google_analytics_id:
# google_site_verification_id:

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: theme:page
      permalink: /:title/
  - scope:
      path: ''
      type: posts
    values:
      layout: theme:post
      permalink: /:year/:month/:day/:title/

include:
  - .htaccess

exclude:
  - Gemfile*
  - Rakefile
  - README.md
  - vendor # Travis CI installs gems into vendor dir and makes Jekyll explode on it

gems:
  - mdotasia-theme
  #- octopress-debugger

repository: https://github.com/mdotasia/coding.maier.asia
