subdomain: coding
prodServer: coding.maier.asia
testServer: coding-test.maier.asia

# config
encoding: utf-8
timezone: America/New_York
highlighter: pygments

include: ['.htaccess']
exclude: ['bower.json', 'coding.maier.asia.iml', 'config.rb', 'Gemfile', 'Gemfile.lock', 'Gruntfile.js', 'node_modules', 'package.json', 'README.md']

# plugins
gems:
  - jekyll-sitemap
