subdomain: coding
source: site
destination: build
prodServer: coding.maier.asia
testServer: coding-test.maier.asia

# config
encoding: utf-8
timezone: America/New_York
markdown: kramdown
pygments: true

include: ['.htaccess']
exclude: ['bower_components','bower.json']

# plugins
gems:
  - jekyll-sitemap
